// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp_Final_1.Data;

#nullable disable

namespace Tp_Final_1.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220803232857_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tp_Final_1.Models.Comentario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPost")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idPost");

                    b.HasIndex("idUser");

                    b.ToTable("Comentario", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            contenido = "Hola todo bien y vos?",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4692),
                            idPost = 1,
                            idUser = 2
                        },
                        new
                        {
                            id = 2,
                            contenido = "Hola como estas?",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4702),
                            idPost = 3,
                            idUser = 2
                        },
                        new
                        {
                            id = 3,
                            contenido = "Hola!!!",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4708),
                            idPost = 3,
                            idUser = 3
                        },
                        new
                        {
                            id = 4,
                            contenido = "Buenas!",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4714),
                            idPost = 5,
                            idUser = 1
                        },
                        new
                        {
                            id = 5,
                            contenido = "Argentina",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4720),
                            idPost = 4,
                            idUser = 3
                        });
                });

            modelBuilder.Entity("Tp_Final_1.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idUser");

                    b.ToTable("Post", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            contenido = "Como estan?",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4647),
                            idUser = 1
                        },
                        new
                        {
                            id = 2,
                            contenido = "Todo bien por suerte",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4668),
                            idUser = 2
                        },
                        new
                        {
                            id = 3,
                            contenido = "Hola",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4673),
                            idUser = 3
                        },
                        new
                        {
                            id = 4,
                            contenido = "De donde son?",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4679),
                            idUser = 4
                        },
                        new
                        {
                            id = 5,
                            contenido = "Hola",
                            fecha = new DateTime(2022, 8, 3, 20, 28, 57, 480, DateTimeKind.Local).AddTicks(4684),
                            idUser = 5
                        });
                });

            modelBuilder.Entity("Tp_Final_1.Models.PostsTags", b =>
                {
                    b.Property<int>("idPost")
                        .HasColumnType("int");

                    b.Property<int>("idTag")
                        .HasColumnType("int");

                    b.HasKey("idPost", "idTag");

                    b.HasIndex("idTag");

                    b.ToTable("Posts_Tags", (string)null);

                    b.HasData(
                        new
                        {
                            idPost = 1,
                            idTag = 5
                        },
                        new
                        {
                            idPost = 1,
                            idTag = 8
                        },
                        new
                        {
                            idPost = 1,
                            idTag = 9
                        },
                        new
                        {
                            idPost = 1,
                            idTag = 3
                        },
                        new
                        {
                            idPost = 2,
                            idTag = 10
                        },
                        new
                        {
                            idPost = 2,
                            idTag = 5
                        },
                        new
                        {
                            idPost = 2,
                            idTag = 9
                        },
                        new
                        {
                            idPost = 2,
                            idTag = 3
                        },
                        new
                        {
                            idPost = 3,
                            idTag = 2
                        },
                        new
                        {
                            idPost = 3,
                            idTag = 5
                        },
                        new
                        {
                            idPost = 3,
                            idTag = 6
                        },
                        new
                        {
                            idPost = 3,
                            idTag = 8
                        },
                        new
                        {
                            idPost = 4,
                            idTag = 8
                        },
                        new
                        {
                            idPost = 4,
                            idTag = 5
                        },
                        new
                        {
                            idPost = 4,
                            idTag = 2
                        },
                        new
                        {
                            idPost = 4,
                            idTag = 1
                        },
                        new
                        {
                            idPost = 5,
                            idTag = 10
                        },
                        new
                        {
                            idPost = 5,
                            idTag = 2
                        },
                        new
                        {
                            idPost = 5,
                            idTag = 5
                        },
                        new
                        {
                            idPost = 5,
                            idTag = 6
                        });
                });

            modelBuilder.Entity("Tp_Final_1.Models.Reaccion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("idPost")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("tipoReaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idPost");

                    b.HasIndex("idUser");

                    b.ToTable("Reaccion", (string)null);
                });

            modelBuilder.Entity("Tp_Final_1.Models.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("palabra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            palabra = "Bienvenida"
                        },
                        new
                        {
                            id = 2,
                            palabra = "love"
                        },
                        new
                        {
                            id = 3,
                            palabra = "instagood"
                        },
                        new
                        {
                            id = 4,
                            palabra = "fashion"
                        },
                        new
                        {
                            id = 5,
                            palabra = "photooftheday"
                        },
                        new
                        {
                            id = 6,
                            palabra = "art"
                        },
                        new
                        {
                            id = 7,
                            palabra = "photography"
                        },
                        new
                        {
                            id = 8,
                            palabra = "instagram"
                        },
                        new
                        {
                            id = 9,
                            palabra = "beautiful"
                        },
                        new
                        {
                            id = 10,
                            palabra = "nature"
                        });
                });

            modelBuilder.Entity("Tp_Final_1.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("isAdm")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "Rojas",
                            bloqueado = false,
                            dni = 111,
                            email = "Mariano@mail.com",
                            intentosFallidos = 0,
                            isAdm = true,
                            nombre = "Mariano",
                            password = "111"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Carballal",
                            bloqueado = false,
                            dni = 222,
                            email = "Alan@mail.com",
                            intentosFallidos = 0,
                            isAdm = false,
                            nombre = "Alan",
                            password = "222"
                        },
                        new
                        {
                            id = 3,
                            apellido = "Fraga",
                            bloqueado = false,
                            dni = 333,
                            email = "Manuel@mail.com",
                            intentosFallidos = 0,
                            isAdm = false,
                            nombre = "Manuel",
                            password = "333"
                        },
                        new
                        {
                            id = 4,
                            apellido = "Lezcano",
                            bloqueado = true,
                            dni = 444,
                            email = "Paula@mail.com",
                            intentosFallidos = 0,
                            isAdm = false,
                            nombre = "Paula",
                            password = "444"
                        },
                        new
                        {
                            id = 5,
                            apellido = "Ghislanzoni",
                            bloqueado = false,
                            dni = 555,
                            email = "Marianog@mail.com",
                            intentosFallidos = 2,
                            isAdm = false,
                            nombre = "Mariano",
                            password = "555"
                        });
                });

            modelBuilder.Entity("Tp_Final_1.Models.UsuarioAmigo", b =>
                {
                    b.Property<int>("idAmigo")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("idAmigo", "idUser");

                    b.HasIndex("idUser");

                    b.ToTable("Usuario_Amigo", (string)null);

                    b.HasData(
                        new
                        {
                            idAmigo = 3,
                            idUser = 2
                        },
                        new
                        {
                            idAmigo = 2,
                            idUser = 3
                        });
                });

            modelBuilder.Entity("Tp_Final_1.Models.Comentario", b =>
                {
                    b.HasOne("Tp_Final_1.Models.Post", "post")
                        .WithMany("comentarios")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tp_Final_1.Models.Usuario", "usuario")
                        .WithMany("misComentarios")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Tp_Final_1.Models.Post", b =>
                {
                    b.HasOne("Tp_Final_1.Models.Usuario", "user")
                        .WithMany("misPosts")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Tp_Final_1.Models.PostsTags", b =>
                {
                    b.HasOne("Tp_Final_1.Models.Post", "Post")
                        .WithMany("PostsTags")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tp_Final_1.Models.Tag", "Tag")
                        .WithMany("PostsTags")
                        .HasForeignKey("idTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Tp_Final_1.Models.Reaccion", b =>
                {
                    b.HasOne("Tp_Final_1.Models.Post", "post")
                        .WithMany("reacciones")
                        .HasForeignKey("idPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tp_Final_1.Models.Usuario", "usuario")
                        .WithMany("misReacciones")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Tp_Final_1.Models.UsuarioAmigo", b =>
                {
                    b.HasOne("Tp_Final_1.Models.Usuario", "user")
                        .WithMany("misAmigos")
                        .HasForeignKey("idAmigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tp_Final_1.Models.Usuario", "amigo")
                        .WithMany("amigosMios")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("amigo");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Tp_Final_1.Models.Post", b =>
                {
                    b.Navigation("PostsTags");

                    b.Navigation("comentarios");

                    b.Navigation("reacciones");
                });

            modelBuilder.Entity("Tp_Final_1.Models.Tag", b =>
                {
                    b.Navigation("PostsTags");
                });

            modelBuilder.Entity("Tp_Final_1.Models.Usuario", b =>
                {
                    b.Navigation("amigosMios");

                    b.Navigation("misAmigos");

                    b.Navigation("misComentarios");

                    b.Navigation("misPosts");

                    b.Navigation("misReacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
